version: "3.1"

services:
  backEndChallenge:
    image: mongo
    container_name: backEndChallenge
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: backend_challenge_db
    volumes:
      - data:/data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  data:
